name: Electron App Packaging

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, windows-latest-x86]

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install dependencies
      run: npm install
    
    - name: Get Version Number
      run: echo "VERSION=$(node -p \"require('./package.json').version\")" >> $GITHUB_ENV

    - name: Build Electron app
      run: npm run build:${{ matrix.os }}

    - name: Upload Release Asset
      uses: actions/upload-release-asset@v1
      if: startsWith(matrix.os, 'ubuntu') || startsWith(matrix.os, 'windows-latest')  
      with:
        upload_url: ${{ github.event.repository.releases_url }}
        asset_name: ${{ github.workspace }}/dist/My Nextron App-${{ env.VERSION }}${{ matrix.os == 'ubuntu-latest' && '.AppImage' || '.exe' }}
        asset_content_type: "application/zip"
      env: 
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
